### ISSUE TITLE
Do the ZMQ package!

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/mason-registry#4]
SParks would be do delighted he'd burst into the sky!  I'll make popcorn!

**Comment by ben-albrecht** [comment]
ZMQ depends on non-Chapel code (ZMQ), so this is also up in the air for `mason 0.1.0`, similar to #3.

**Comment by ben-albrecht** [comment]
I'm going to close this as a duplicate of the broader issue: https://github.com/chapel-lang/chapel/issues/10713
